// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_GetUsageSession_FullMethodName      = "/telemetry.TelemetryService/GetUsageSession"
	TelemetryService_ListUserSessions_FullMethodName     = "/telemetry.TelemetryService/ListUserSessions"
	TelemetryService_GetUsageStats_FullMethodName        = "/telemetry.TelemetryService/GetUsageStats"
	TelemetryService_GetAssetUsageHistory_FullMethodName = "/telemetry.TelemetryService/GetAssetUsageHistory"
	TelemetryService_GetSystemUsageStats_FullMethodName  = "/telemetry.TelemetryService/GetSystemUsageStats"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	GetUsageSession(ctx context.Context, in *GetUsageSessionRequest, opts ...grpc.CallOption) (*UsageSessionResponse, error)
	ListUserSessions(ctx context.Context, in *ListUserSessionsRequest, opts ...grpc.CallOption) (*ListUserSessionsResponse, error)
	GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*UsageStatsResponse, error)
	GetAssetUsageHistory(ctx context.Context, in *GetAssetUsageHistoryRequest, opts ...grpc.CallOption) (*GetAssetUsageHistoryResponse, error)
	GetSystemUsageStats(ctx context.Context, in *GetSystemUsageStatsRequest, opts ...grpc.CallOption) (*SystemUsageStatsResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) GetUsageSession(ctx context.Context, in *GetUsageSessionRequest, opts ...grpc.CallOption) (*UsageSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageSessionResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetUsageSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) ListUserSessions(ctx context.Context, in *ListUserSessionsRequest, opts ...grpc.CallOption) (*ListUserSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserSessionsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ListUserSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetUsageStats(ctx context.Context, in *GetUsageStatsRequest, opts ...grpc.CallOption) (*UsageStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageStatsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetAssetUsageHistory(ctx context.Context, in *GetAssetUsageHistoryRequest, opts ...grpc.CallOption) (*GetAssetUsageHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetUsageHistoryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetAssetUsageHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetSystemUsageStats(ctx context.Context, in *GetSystemUsageStatsRequest, opts ...grpc.CallOption) (*SystemUsageStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemUsageStatsResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetSystemUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
type TelemetryServiceServer interface {
	GetUsageSession(context.Context, *GetUsageSessionRequest) (*UsageSessionResponse, error)
	ListUserSessions(context.Context, *ListUserSessionsRequest) (*ListUserSessionsResponse, error)
	GetUsageStats(context.Context, *GetUsageStatsRequest) (*UsageStatsResponse, error)
	GetAssetUsageHistory(context.Context, *GetAssetUsageHistoryRequest) (*GetAssetUsageHistoryResponse, error)
	GetSystemUsageStats(context.Context, *GetSystemUsageStatsRequest) (*SystemUsageStatsResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) GetUsageSession(context.Context, *GetUsageSessionRequest) (*UsageSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageSession not implemented")
}
func (UnimplementedTelemetryServiceServer) ListUserSessions(context.Context, *ListUserSessionsRequest) (*ListUserSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserSessions not implemented")
}
func (UnimplementedTelemetryServiceServer) GetUsageStats(context.Context, *GetUsageStatsRequest) (*UsageStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsageStats not implemented")
}
func (UnimplementedTelemetryServiceServer) GetAssetUsageHistory(context.Context, *GetAssetUsageHistoryRequest) (*GetAssetUsageHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetUsageHistory not implemented")
}
func (UnimplementedTelemetryServiceServer) GetSystemUsageStats(context.Context, *GetSystemUsageStatsRequest) (*SystemUsageStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemUsageStats not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_GetUsageSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetUsageSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetUsageSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetUsageSession(ctx, req.(*GetUsageSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_ListUserSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ListUserSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ListUserSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ListUserSessions(ctx, req.(*ListUserSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetUsageStats(ctx, req.(*GetUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetAssetUsageHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetUsageHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetAssetUsageHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetAssetUsageHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetAssetUsageHistory(ctx, req.(*GetAssetUsageHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetSystemUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetSystemUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetSystemUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetSystemUsageStats(ctx, req.(*GetSystemUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsageSession",
			Handler:    _TelemetryService_GetUsageSession_Handler,
		},
		{
			MethodName: "ListUserSessions",
			Handler:    _TelemetryService_ListUserSessions_Handler,
		},
		{
			MethodName: "GetUsageStats",
			Handler:    _TelemetryService_GetUsageStats_Handler,
		},
		{
			MethodName: "GetAssetUsageHistory",
			Handler:    _TelemetryService_GetAssetUsageHistory_Handler,
		},
		{
			MethodName: "GetSystemUsageStats",
			Handler:    _TelemetryService_GetSystemUsageStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telemetry.proto",
}
