// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsageSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageSessionRequest) Reset() {
	*x = GetUsageSessionRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageSessionRequest) ProtoMessage() {}

func (x *GetUsageSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageSessionRequest.ProtoReflect.Descriptor instead.
func (*GetUsageSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsageSessionRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ListUserSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsRequest) Reset() {
	*x = ListUserSessionsRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsRequest) ProtoMessage() {}

func (x *ListUserSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListUserSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserSessionsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sessions      []*UsageSessionResponse `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserSessionsResponse) Reset() {
	*x = ListUserSessionsResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserSessionsResponse) ProtoMessage() {}

func (x *ListUserSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListUserSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ListUserSessionsResponse) GetSessions() []*UsageSessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type GetSystemUsageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemUsageStatsRequest) Reset() {
	*x = GetSystemUsageStatsRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemUsageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemUsageStatsRequest) ProtoMessage() {}

func (x *GetSystemUsageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemUsageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemUsageStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{3}
}

type SystemUsageStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetStats    []*AssetUsageStats     `protobuf:"bytes,1,rep,name=asset_stats,json=assetStats,proto3" json:"asset_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemUsageStatsResponse) Reset() {
	*x = SystemUsageStatsResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemUsageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUsageStatsResponse) ProtoMessage() {}

func (x *SystemUsageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUsageStatsResponse.ProtoReflect.Descriptor instead.
func (*SystemUsageStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *SystemUsageStatsResponse) GetAssetStats() []*AssetUsageStats {
	if x != nil {
		return x.AssetStats
	}
	return nil
}

type AssetUsageStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AssetId            string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	TotalSessions      int32                  `protobuf:"varint,2,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	AvgDurationMinutes int32                  `protobuf:"varint,3,opt,name=avg_duration_minutes,json=avgDurationMinutes,proto3" json:"avg_duration_minutes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssetUsageStats) Reset() {
	*x = AssetUsageStats{}
	mi := &file_proto_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUsageStats) ProtoMessage() {}

func (x *AssetUsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUsageStats.ProtoReflect.Descriptor instead.
func (*AssetUsageStats) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *AssetUsageStats) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetUsageStats) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *AssetUsageStats) GetAvgDurationMinutes() int32 {
	if x != nil {
		return x.AvgDurationMinutes
	}
	return 0
}

type GetUsageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatsRequest) Reset() {
	*x = GetUsageStatsRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatsRequest) ProtoMessage() {}

func (x *GetUsageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsageStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UsageStatsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TotalSessions        int32                  `protobuf:"varint,1,opt,name=total_sessions,json=totalSessions,proto3" json:"total_sessions,omitempty"`
	TotalDurationMinutes int32                  `protobuf:"varint,2,opt,name=total_duration_minutes,json=totalDurationMinutes,proto3" json:"total_duration_minutes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UsageStatsResponse) Reset() {
	*x = UsageStatsResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStatsResponse) ProtoMessage() {}

func (x *UsageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStatsResponse.ProtoReflect.Descriptor instead.
func (*UsageStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *UsageStatsResponse) GetTotalSessions() int32 {
	if x != nil {
		return x.TotalSessions
	}
	return 0
}

func (x *UsageStatsResponse) GetTotalDurationMinutes() int32 {
	if x != nil {
		return x.TotalDurationMinutes
	}
	return 0
}

type GetAssetUsageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetUsageHistoryRequest) Reset() {
	*x = GetAssetUsageHistoryRequest{}
	mi := &file_proto_telemetry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetUsageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetUsageHistoryRequest) ProtoMessage() {}

func (x *GetAssetUsageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetUsageHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetAssetUsageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *GetAssetUsageHistoryRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type GetAssetUsageHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sessions      []*UsageSessionResponse `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetUsageHistoryResponse) Reset() {
	*x = GetAssetUsageHistoryResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetUsageHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetUsageHistoryResponse) ProtoMessage() {}

func (x *GetAssetUsageHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetUsageHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetAssetUsageHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{9}
}

func (x *GetAssetUsageHistoryResponse) GetSessions() []*UsageSessionResponse {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type UsageSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BookingId       string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId         string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StartedAt       string                 `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt         string                 `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UsageSessionResponse) Reset() {
	*x = UsageSessionResponse{}
	mi := &file_proto_telemetry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageSessionResponse) ProtoMessage() {}

func (x *UsageSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageSessionResponse.ProtoReflect.Descriptor instead.
func (*UsageSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_proto_rawDescGZIP(), []int{10}
}

func (x *UsageSessionResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *UsageSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UsageSessionResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UsageSessionResponse) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *UsageSessionResponse) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *UsageSessionResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

var File_proto_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telemetry.proto\x12\ttelemetry\"7\n" +
	"\x16GetUsageSessionRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"2\n" +
	"\x17ListUserSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x18ListUserSessionsResponse\x12;\n" +
	"\bsessions\x18\x01 \x03(\v2\x1f.telemetry.UsageSessionResponseR\bsessions\"\x1c\n" +
	"\x1aGetSystemUsageStatsRequest\"W\n" +
	"\x18SystemUsageStatsResponse\x12;\n" +
	"\vasset_stats\x18\x01 \x03(\v2\x1a.telemetry.AssetUsageStatsR\n" +
	"assetStats\"\x85\x01\n" +
	"\x0fAssetUsageStats\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12%\n" +
	"\x0etotal_sessions\x18\x02 \x01(\x05R\rtotalSessions\x120\n" +
	"\x14avg_duration_minutes\x18\x03 \x01(\x05R\x12avgDurationMinutes\"/\n" +
	"\x14GetUsageStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"q\n" +
	"\x12UsageStatsResponse\x12%\n" +
	"\x0etotal_sessions\x18\x01 \x01(\x05R\rtotalSessions\x124\n" +
	"\x16total_duration_minutes\x18\x02 \x01(\x05R\x14totalDurationMinutes\"8\n" +
	"\x1bGetAssetUsageHistoryRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"[\n" +
	"\x1cGetAssetUsageHistoryResponse\x12;\n" +
	"\bsessions\x18\x01 \x03(\v2\x1f.telemetry.UsageSessionResponseR\bsessions\"\xce\x01\n" +
	"\x14UsageSessionResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tR\tstartedAt\x12\x19\n" +
	"\bended_at\x18\x05 \x01(\tR\aendedAt\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x05R\x0fdurationMinutes2\xe3\x03\n" +
	"\x10TelemetryService\x12U\n" +
	"\x0fGetUsageSession\x12!.telemetry.GetUsageSessionRequest\x1a\x1f.telemetry.UsageSessionResponse\x12[\n" +
	"\x10ListUserSessions\x12\".telemetry.ListUserSessionsRequest\x1a#.telemetry.ListUserSessionsResponse\x12O\n" +
	"\rGetUsageStats\x12\x1f.telemetry.GetUsageStatsRequest\x1a\x1d.telemetry.UsageStatsResponse\x12g\n" +
	"\x14GetAssetUsageHistory\x12&.telemetry.GetAssetUsageHistoryRequest\x1a'.telemetry.GetAssetUsageHistoryResponse\x12a\n" +
	"\x13GetSystemUsageStats\x12%.telemetry.GetSystemUsageStatsRequest\x1a#.telemetry.SystemUsageStatsResponseB2Z0gym-membership/telemetry-service/proto;telemetryb\x06proto3"

var (
	file_proto_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_proto_rawDescData
}

var file_proto_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_telemetry_proto_goTypes = []any{
	(*GetUsageSessionRequest)(nil),       // 0: telemetry.GetUsageSessionRequest
	(*ListUserSessionsRequest)(nil),      // 1: telemetry.ListUserSessionsRequest
	(*ListUserSessionsResponse)(nil),     // 2: telemetry.ListUserSessionsResponse
	(*GetSystemUsageStatsRequest)(nil),   // 3: telemetry.GetSystemUsageStatsRequest
	(*SystemUsageStatsResponse)(nil),     // 4: telemetry.SystemUsageStatsResponse
	(*AssetUsageStats)(nil),              // 5: telemetry.AssetUsageStats
	(*GetUsageStatsRequest)(nil),         // 6: telemetry.GetUsageStatsRequest
	(*UsageStatsResponse)(nil),           // 7: telemetry.UsageStatsResponse
	(*GetAssetUsageHistoryRequest)(nil),  // 8: telemetry.GetAssetUsageHistoryRequest
	(*GetAssetUsageHistoryResponse)(nil), // 9: telemetry.GetAssetUsageHistoryResponse
	(*UsageSessionResponse)(nil),         // 10: telemetry.UsageSessionResponse
}
var file_proto_telemetry_proto_depIdxs = []int32{
	10, // 0: telemetry.ListUserSessionsResponse.sessions:type_name -> telemetry.UsageSessionResponse
	5,  // 1: telemetry.SystemUsageStatsResponse.asset_stats:type_name -> telemetry.AssetUsageStats
	10, // 2: telemetry.GetAssetUsageHistoryResponse.sessions:type_name -> telemetry.UsageSessionResponse
	0,  // 3: telemetry.TelemetryService.GetUsageSession:input_type -> telemetry.GetUsageSessionRequest
	1,  // 4: telemetry.TelemetryService.ListUserSessions:input_type -> telemetry.ListUserSessionsRequest
	6,  // 5: telemetry.TelemetryService.GetUsageStats:input_type -> telemetry.GetUsageStatsRequest
	8,  // 6: telemetry.TelemetryService.GetAssetUsageHistory:input_type -> telemetry.GetAssetUsageHistoryRequest
	3,  // 7: telemetry.TelemetryService.GetSystemUsageStats:input_type -> telemetry.GetSystemUsageStatsRequest
	10, // 8: telemetry.TelemetryService.GetUsageSession:output_type -> telemetry.UsageSessionResponse
	2,  // 9: telemetry.TelemetryService.ListUserSessions:output_type -> telemetry.ListUserSessionsResponse
	7,  // 10: telemetry.TelemetryService.GetUsageStats:output_type -> telemetry.UsageStatsResponse
	9,  // 11: telemetry.TelemetryService.GetAssetUsageHistory:output_type -> telemetry.GetAssetUsageHistoryResponse
	4,  // 12: telemetry.TelemetryService.GetSystemUsageStats:output_type -> telemetry.SystemUsageStatsResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_telemetry_proto_init() }
func file_proto_telemetry_proto_init() {
	if File_proto_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_proto_rawDesc), len(file_proto_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_proto = out.File
	file_proto_telemetry_proto_goTypes = nil
	file_proto_telemetry_proto_depIdxs = nil
}
