// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: telemetry/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAccessRequest) Reset() {
	*x = RecordAccessRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAccessRequest) ProtoMessage() {}

func (x *RecordAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAccessRequest.ProtoReflect.Descriptor instead.
func (*RecordAccessRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{0}
}

type GetUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{1}
}

type UsageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_telemetry_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{2}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{3}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_telemetry_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{4}
}

type LogEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEventRequest) Reset() {
	*x = LogEventRequest{}
	mi := &file_telemetry_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEventRequest) ProtoMessage() {}

func (x *LogEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEventRequest.ProtoReflect.Descriptor instead.
func (*LogEventRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{5}
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_telemetry_telemetry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_telemetry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_telemetry_proto_rawDescGZIP(), []int{6}
}

var File_telemetry_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x19telemetry/telemetry.proto\x12\ttelemetry\"\x15\n" +
	"\x13RecordAccessRequest\"\x11\n" +
	"\x0fGetUsageRequest\"\f\n" +
	"\n" +
	"UsageStats\"\x12\n" +
	"\x10HeartbeatRequest\"\x13\n" +
	"\x11HeartbeatResponse\"\x11\n" +
	"\x0fLogEventRequest\"\x13\n" +
	"\x11TelemetryResponse2\xb2\x02\n" +
	"\x10TelemetryService\x12L\n" +
	"\fRecordAccess\x12\x1e.telemetry.RecordAccessRequest\x1a\x1c.telemetry.TelemetryResponse\x12B\n" +
	"\rGetUsageStats\x12\x1a.telemetry.GetUsageRequest\x1a\x15.telemetry.UsageStats\x12F\n" +
	"\tHeartbeat\x12\x1b.telemetry.HeartbeatRequest\x1a\x1c.telemetry.HeartbeatResponse\x12D\n" +
	"\bLogEvent\x12\x1a.telemetry.LogEventRequest\x1a\x1c.telemetry.TelemetryResponseB\rZ\v./telemetryb\x06proto3"

var (
	file_telemetry_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_telemetry_proto_rawDescData []byte
)

func file_telemetry_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_telemetry_proto_rawDesc), len(file_telemetry_telemetry_proto_rawDesc)))
	})
	return file_telemetry_telemetry_proto_rawDescData
}

var file_telemetry_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_telemetry_telemetry_proto_goTypes = []any{
	(*RecordAccessRequest)(nil), // 0: telemetry.RecordAccessRequest
	(*GetUsageRequest)(nil),     // 1: telemetry.GetUsageRequest
	(*UsageStats)(nil),          // 2: telemetry.UsageStats
	(*HeartbeatRequest)(nil),    // 3: telemetry.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 4: telemetry.HeartbeatResponse
	(*LogEventRequest)(nil),     // 5: telemetry.LogEventRequest
	(*TelemetryResponse)(nil),   // 6: telemetry.TelemetryResponse
}
var file_telemetry_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.TelemetryService.RecordAccess:input_type -> telemetry.RecordAccessRequest
	1, // 1: telemetry.TelemetryService.GetUsageStats:input_type -> telemetry.GetUsageRequest
	3, // 2: telemetry.TelemetryService.Heartbeat:input_type -> telemetry.HeartbeatRequest
	5, // 3: telemetry.TelemetryService.LogEvent:input_type -> telemetry.LogEventRequest
	6, // 4: telemetry.TelemetryService.RecordAccess:output_type -> telemetry.TelemetryResponse
	2, // 5: telemetry.TelemetryService.GetUsageStats:output_type -> telemetry.UsageStats
	4, // 6: telemetry.TelemetryService.Heartbeat:output_type -> telemetry.HeartbeatResponse
	6, // 7: telemetry.TelemetryService.LogEvent:output_type -> telemetry.TelemetryResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_telemetry_telemetry_proto_init() }
func file_telemetry_telemetry_proto_init() {
	if File_telemetry_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_telemetry_proto_rawDesc), len(file_telemetry_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_telemetry_proto = out.File
	file_telemetry_telemetry_proto_goTypes = nil
	file_telemetry_telemetry_proto_depIdxs = nil
}
