syntax = "proto3";

package membership;
option go_package = "./membership";

service MembershipService {
  rpc CreateMembership(CreateMembershipRequest) returns (Membership);
  rpc GetMembership(GetMembershipRequest) returns (Membership);
  rpc CancelMembership(CancelMembershipRequest) returns (Membership);
  rpc ValidateAccess(ValidateAccessRequest) returns (ValidateAccessResponse);
}

message Membership {}
message CreateMembershipRequest {}
message GetMembershipRequest {}
message CancelMembershipRequest {}
message ValidateAccessRequest {}
message ValidateAccessResponse {}
