// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: membership/membership.proto

package membership

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipService_CreateBooking_FullMethodName         = "/membership.MembershipService/CreateBooking"
	MembershipService_CancelBooking_FullMethodName         = "/membership.MembershipService/CancelBooking"
	MembershipService_ReturnBooking_FullMethodName         = "/membership.MembershipService/ReturnBooking"
	MembershipService_GetUserCredits_FullMethodName        = "/membership.MembershipService/GetUserCredits"
	MembershipService_DeductCredits_FullMethodName         = "/membership.MembershipService/DeductCredits"
	MembershipService_GetUserBookings_FullMethodName       = "/membership.MembershipService/GetUserBookings"
	MembershipService_AddCredits_FullMethodName            = "/membership.MembershipService/AddCredits"
	MembershipService_CreateUser_FullMethodName            = "/membership.MembershipService/CreateUser"
	MembershipService_GetUser_FullMethodName               = "/membership.MembershipService/GetUser"
	MembershipService_UpdateUser_FullMethodName            = "/membership.MembershipService/UpdateUser"
	MembershipService_GetUserMembership_FullMethodName     = "/membership.MembershipService/GetUserMembership"
	MembershipService_GetCreditTransactions_FullMethodName = "/membership.MembershipService/GetCreditTransactions"
)

// MembershipServiceClient is the client API for MembershipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembershipServiceClient interface {
	// Existing 7 methods
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*Booking, error)
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*Booking, error)
	ReturnBooking(ctx context.Context, in *ReturnBookingRequest, opts ...grpc.CallOption) (*Booking, error)
	GetUserCredits(ctx context.Context, in *GetUserCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error)
	DeductCredits(ctx context.Context, in *DeductCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error)
	GetUserBookings(ctx context.Context, in *GetUserBookingsRequest, opts ...grpc.CallOption) (*BookingList, error)
	AddCredits(ctx context.Context, in *AddCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error)
	// 5 New methods to reach exactly 12 endpoints
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetUserMembership(ctx context.Context, in *GetUserMembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error)
	GetCreditTransactions(ctx context.Context, in *GetCreditTransactionsRequest, opts ...grpc.CallOption) (*TransactionListResponse, error)
}

type membershipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipServiceClient(cc grpc.ClientConnInterface) MembershipServiceClient {
	return &membershipServiceClient{cc}
}

func (c *membershipServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Booking)
	err := c.cc.Invoke(ctx, MembershipService_CreateBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Booking)
	err := c.cc.Invoke(ctx, MembershipService_CancelBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) ReturnBooking(ctx context.Context, in *ReturnBookingRequest, opts ...grpc.CallOption) (*Booking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Booking)
	err := c.cc.Invoke(ctx, MembershipService_ReturnBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetUserCredits(ctx context.Context, in *GetUserCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditsResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetUserCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) DeductCredits(ctx context.Context, in *DeductCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditsResponse)
	err := c.cc.Invoke(ctx, MembershipService_DeductCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetUserBookings(ctx context.Context, in *GetUserBookingsRequest, opts ...grpc.CallOption) (*BookingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingList)
	err := c.cc.Invoke(ctx, MembershipService_GetUserBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) AddCredits(ctx context.Context, in *AddCreditsRequest, opts ...grpc.CallOption) (*CreditsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditsResponse)
	err := c.cc.Invoke(ctx, MembershipService_AddCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, MembershipService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, MembershipService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetUserMembership(ctx context.Context, in *GetUserMembershipRequest, opts ...grpc.CallOption) (*MembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembershipResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetUserMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipServiceClient) GetCreditTransactions(ctx context.Context, in *GetCreditTransactionsRequest, opts ...grpc.CallOption) (*TransactionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionListResponse)
	err := c.cc.Invoke(ctx, MembershipService_GetCreditTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipServiceServer is the server API for MembershipService service.
// All implementations must embed UnimplementedMembershipServiceServer
// for forward compatibility.
type MembershipServiceServer interface {
	// Existing 7 methods
	CreateBooking(context.Context, *CreateBookingRequest) (*Booking, error)
	CancelBooking(context.Context, *CancelBookingRequest) (*Booking, error)
	ReturnBooking(context.Context, *ReturnBookingRequest) (*Booking, error)
	GetUserCredits(context.Context, *GetUserCreditsRequest) (*CreditsResponse, error)
	DeductCredits(context.Context, *DeductCreditsRequest) (*CreditsResponse, error)
	GetUserBookings(context.Context, *GetUserBookingsRequest) (*BookingList, error)
	AddCredits(context.Context, *AddCreditsRequest) (*CreditsResponse, error)
	// 5 New methods to reach exactly 12 endpoints
	CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error)
	GetUserMembership(context.Context, *GetUserMembershipRequest) (*MembershipResponse, error)
	GetCreditTransactions(context.Context, *GetCreditTransactionsRequest) (*TransactionListResponse, error)
	mustEmbedUnimplementedMembershipServiceServer()
}

// UnimplementedMembershipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipServiceServer struct{}

func (UnimplementedMembershipServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*Booking, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedMembershipServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*Booking, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedMembershipServiceServer) ReturnBooking(context.Context, *ReturnBookingRequest) (*Booking, error) {
	return nil, status.Error(codes.Unimplemented, "method ReturnBooking not implemented")
}
func (UnimplementedMembershipServiceServer) GetUserCredits(context.Context, *GetUserCreditsRequest) (*CreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCredits not implemented")
}
func (UnimplementedMembershipServiceServer) DeductCredits(context.Context, *DeductCreditsRequest) (*CreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductCredits not implemented")
}
func (UnimplementedMembershipServiceServer) GetUserBookings(context.Context, *GetUserBookingsRequest) (*BookingList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserBookings not implemented")
}
func (UnimplementedMembershipServiceServer) AddCredits(context.Context, *AddCreditsRequest) (*CreditsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCredits not implemented")
}
func (UnimplementedMembershipServiceServer) CreateUser(context.Context, *CreateUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedMembershipServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedMembershipServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedMembershipServiceServer) GetUserMembership(context.Context, *GetUserMembershipRequest) (*MembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserMembership not implemented")
}
func (UnimplementedMembershipServiceServer) GetCreditTransactions(context.Context, *GetCreditTransactionsRequest) (*TransactionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreditTransactions not implemented")
}
func (UnimplementedMembershipServiceServer) mustEmbedUnimplementedMembershipServiceServer() {}
func (UnimplementedMembershipServiceServer) testEmbeddedByValue()                           {}

// UnsafeMembershipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipServiceServer will
// result in compilation errors.
type UnsafeMembershipServiceServer interface {
	mustEmbedUnimplementedMembershipServiceServer()
}

func RegisterMembershipServiceServer(s grpc.ServiceRegistrar, srv MembershipServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipService_ServiceDesc, srv)
}

func _MembershipService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CreateBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CancelBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_ReturnBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).ReturnBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_ReturnBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).ReturnBooking(ctx, req.(*ReturnBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetUserCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetUserCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetUserCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetUserCredits(ctx, req.(*GetUserCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_DeductCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).DeductCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_DeductCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).DeductCredits(ctx, req.(*DeductCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetUserBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetUserBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetUserBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetUserBookings(ctx, req.(*GetUserBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_AddCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCreditsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).AddCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_AddCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).AddCredits(ctx, req.(*AddCreditsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetUserMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetUserMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetUserMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetUserMembership(ctx, req.(*GetUserMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipService_GetCreditTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipServiceServer).GetCreditTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipService_GetCreditTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipServiceServer).GetCreditTransactions(ctx, req.(*GetCreditTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipService_ServiceDesc is the grpc.ServiceDesc for MembershipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "membership.MembershipService",
	HandlerType: (*MembershipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooking",
			Handler:    _MembershipService_CreateBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _MembershipService_CancelBooking_Handler,
		},
		{
			MethodName: "ReturnBooking",
			Handler:    _MembershipService_ReturnBooking_Handler,
		},
		{
			MethodName: "GetUserCredits",
			Handler:    _MembershipService_GetUserCredits_Handler,
		},
		{
			MethodName: "DeductCredits",
			Handler:    _MembershipService_DeductCredits_Handler,
		},
		{
			MethodName: "GetUserBookings",
			Handler:    _MembershipService_GetUserBookings_Handler,
		},
		{
			MethodName: "AddCredits",
			Handler:    _MembershipService_AddCredits_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _MembershipService_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _MembershipService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _MembershipService_UpdateUser_Handler,
		},
		{
			MethodName: "GetUserMembership",
			Handler:    _MembershipService_GetUserMembership_Handler,
		},
		{
			MethodName: "GetCreditTransactions",
			Handler:    _MembershipService_GetCreditTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "membership/membership.proto",
}
