// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: membership.proto

package membership

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Membership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartDate     string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Membership) Reset() {
	*x = Membership{}
	mi := &file_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Membership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Membership) ProtoMessage() {}

func (x *Membership) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Membership.ProtoReflect.Descriptor instead.
func (*Membership) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{0}
}

func (x *Membership) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Membership) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Membership) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Membership) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Membership) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Membership) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type CreateMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMembershipRequest) Reset() {
	*x = CreateMembershipRequest{}
	mi := &file_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMembershipRequest) ProtoMessage() {}

func (x *CreateMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMembershipRequest.ProtoReflect.Descriptor instead.
func (*CreateMembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMembershipRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMembershipRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateMembershipRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateMembershipRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{2}
}

func (x *GetMembershipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMembershipRequest) Reset() {
	*x = CancelMembershipRequest{}
	mi := &file_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMembershipRequest) ProtoMessage() {}

func (x *CancelMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMembershipRequest.ProtoReflect.Descriptor instead.
func (*CancelMembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{3}
}

func (x *CancelMembershipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ValidateAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessRequest) Reset() {
	*x = ValidateAccessRequest{}
	mi := &file_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessRequest) ProtoMessage() {}

func (x *ValidateAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccessRequest) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAccessRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type ValidateAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccessResponse) Reset() {
	*x = ValidateAccessResponse{}
	mi := &file_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccessResponse) ProtoMessage() {}

func (x *ValidateAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccessResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccessResponse) Descriptor() ([]byte, []int) {
	return file_membership_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

var File_membership_proto protoreflect.FileDescriptor

const file_membership_proto_rawDesc = "" +
	"\n" +
	"\x10membership.proto\x12\n" +
	"membership\"\xa2\x01\n" +
	"\n" +
	"Membership\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\"\x87\x01\n" +
	"\x17CreateMembershipRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"&\n" +
	"\x14GetMembershipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17CancelMembershipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"K\n" +
	"\x15ValidateAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"7\n" +
	"\x16ValidateAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess2\xd9\x02\n" +
	"\x11MembershipService\x12O\n" +
	"\x10CreateMembership\x12#.membership.CreateMembershipRequest\x1a\x16.membership.Membership\x12I\n" +
	"\rGetMembership\x12 .membership.GetMembershipRequest\x1a\x16.membership.Membership\x12O\n" +
	"\x10CancelMembership\x12#.membership.CancelMembershipRequest\x1a\x16.membership.Membership\x12W\n" +
	"\x0eValidateAccess\x12!.membership.ValidateAccessRequest\x1a\".membership.ValidateAccessResponseB\x0eZ\f./membershipb\x06proto3"

var (
	file_membership_proto_rawDescOnce sync.Once
	file_membership_proto_rawDescData []byte
)

func file_membership_proto_rawDescGZIP() []byte {
	file_membership_proto_rawDescOnce.Do(func() {
		file_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membership_proto_rawDesc), len(file_membership_proto_rawDesc)))
	})
	return file_membership_proto_rawDescData
}

var file_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_membership_proto_goTypes = []any{
	(*Membership)(nil),              // 0: membership.Membership
	(*CreateMembershipRequest)(nil), // 1: membership.CreateMembershipRequest
	(*GetMembershipRequest)(nil),    // 2: membership.GetMembershipRequest
	(*CancelMembershipRequest)(nil), // 3: membership.CancelMembershipRequest
	(*ValidateAccessRequest)(nil),   // 4: membership.ValidateAccessRequest
	(*ValidateAccessResponse)(nil),  // 5: membership.ValidateAccessResponse
}
var file_membership_proto_depIdxs = []int32{
	1, // 0: membership.MembershipService.CreateMembership:input_type -> membership.CreateMembershipRequest
	2, // 1: membership.MembershipService.GetMembership:input_type -> membership.GetMembershipRequest
	3, // 2: membership.MembershipService.CancelMembership:input_type -> membership.CancelMembershipRequest
	4, // 3: membership.MembershipService.ValidateAccess:input_type -> membership.ValidateAccessRequest
	0, // 4: membership.MembershipService.CreateMembership:output_type -> membership.Membership
	0, // 5: membership.MembershipService.GetMembership:output_type -> membership.Membership
	0, // 6: membership.MembershipService.CancelMembership:output_type -> membership.Membership
	5, // 7: membership.MembershipService.ValidateAccess:output_type -> membership.ValidateAccessResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_membership_proto_init() }
func file_membership_proto_init() {
	if File_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membership_proto_rawDesc), len(file_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membership_proto_goTypes,
		DependencyIndexes: file_membership_proto_depIdxs,
		MessageInfos:      file_membership_proto_msgTypes,
	}.Build()
	File_membership_proto = out.File
	file_membership_proto_goTypes = nil
	file_membership_proto_depIdxs = nil
}
