// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/membership/membership.proto

package membership

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,3,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_proto_membership_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Booking) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Booking) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Booking) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StartTime     string                 `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBookingRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateBookingRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateBookingRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{2}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type ReturnBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnBookingRequest) Reset() {
	*x = ReturnBookingRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnBookingRequest) ProtoMessage() {}

func (x *ReturnBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnBookingRequest.ProtoReflect.Descriptor instead.
func (*ReturnBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetUserCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCreditsRequest) Reset() {
	*x = GetUserCreditsRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCreditsRequest) ProtoMessage() {}

func (x *GetUserCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCreditsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCreditsRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserCreditsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeductCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductCreditsRequest) Reset() {
	*x = DeductCreditsRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductCreditsRequest) ProtoMessage() {}

func (x *DeductCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductCreditsRequest.ProtoReflect.Descriptor instead.
func (*DeductCreditsRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{5}
}

func (x *DeductCreditsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeductCreditsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddCreditsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCreditsRequest) Reset() {
	*x = AddCreditsRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCreditsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCreditsRequest) ProtoMessage() {}

func (x *AddCreditsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCreditsRequest.ProtoReflect.Descriptor instead.
func (*AddCreditsRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{6}
}

func (x *AddCreditsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddCreditsRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreditsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       int32                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditsResponse) Reset() {
	*x = CreditsResponse{}
	mi := &file_proto_membership_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditsResponse) ProtoMessage() {}

func (x *CreditsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditsResponse.ProtoReflect.Descriptor instead.
func (*CreditsResponse) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{7}
}

func (x *CreditsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreditsResponse) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetUserBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBookingsRequest) Reset() {
	*x = GetUserBookingsRequest{}
	mi := &file_proto_membership_membership_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBookingsRequest) ProtoMessage() {}

func (x *GetUserBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserBookingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserBookingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BookingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingList) Reset() {
	*x = BookingList{}
	mi := &file_proto_membership_membership_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingList) ProtoMessage() {}

func (x *BookingList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_membership_membership_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingList.ProtoReflect.Descriptor instead.
func (*BookingList) Descriptor() ([]byte, []int) {
	return file_proto_membership_membership_proto_rawDescGZIP(), []int{9}
}

func (x *BookingList) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

var File_proto_membership_membership_proto protoreflect.FileDescriptor

const file_proto_membership_membership_proto_rawDesc = "" +
	"\n" +
	"!proto/membership/membership.proto\x12\n" +
	"membership\"\x9f\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x03 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"\x84\x01\n" +
	"\x14CreateBookingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\tR\aendTime\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"5\n" +
	"\x14ReturnBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"0\n" +
	"\x15GetUserCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x14DeductCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"D\n" +
	"\x11AddCreditsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"D\n" +
	"\x0fCreditsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x05R\abalance\"1\n" +
	"\x16GetUserBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\">\n" +
	"\vBookingList\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.membership.BookingR\bbookings2\xa7\x04\n" +
	"\x11MembershipService\x12F\n" +
	"\rCreateBooking\x12 .membership.CreateBookingRequest\x1a\x13.membership.Booking\x12F\n" +
	"\rCancelBooking\x12 .membership.CancelBookingRequest\x1a\x13.membership.Booking\x12F\n" +
	"\rReturnBooking\x12 .membership.ReturnBookingRequest\x1a\x13.membership.Booking\x12P\n" +
	"\x0eGetUserCredits\x12!.membership.GetUserCreditsRequest\x1a\x1b.membership.CreditsResponse\x12N\n" +
	"\rDeductCredits\x12 .membership.DeductCreditsRequest\x1a\x1b.membership.CreditsResponse\x12N\n" +
	"\x0fGetUserBookings\x12\".membership.GetUserBookingsRequest\x1a\x17.membership.BookingList\x12H\n" +
	"\n" +
	"AddCredits\x12\x1d.membership.AddCreditsRequest\x1a\x1b.membership.CreditsResponseB\x0eZ\f./membershipb\x06proto3"

var (
	file_proto_membership_membership_proto_rawDescOnce sync.Once
	file_proto_membership_membership_proto_rawDescData []byte
)

func file_proto_membership_membership_proto_rawDescGZIP() []byte {
	file_proto_membership_membership_proto_rawDescOnce.Do(func() {
		file_proto_membership_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_membership_membership_proto_rawDesc), len(file_proto_membership_membership_proto_rawDesc)))
	})
	return file_proto_membership_membership_proto_rawDescData
}

var file_proto_membership_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_membership_membership_proto_goTypes = []any{
	(*Booking)(nil),                // 0: membership.Booking
	(*CreateBookingRequest)(nil),   // 1: membership.CreateBookingRequest
	(*CancelBookingRequest)(nil),   // 2: membership.CancelBookingRequest
	(*ReturnBookingRequest)(nil),   // 3: membership.ReturnBookingRequest
	(*GetUserCreditsRequest)(nil),  // 4: membership.GetUserCreditsRequest
	(*DeductCreditsRequest)(nil),   // 5: membership.DeductCreditsRequest
	(*AddCreditsRequest)(nil),      // 6: membership.AddCreditsRequest
	(*CreditsResponse)(nil),        // 7: membership.CreditsResponse
	(*GetUserBookingsRequest)(nil), // 8: membership.GetUserBookingsRequest
	(*BookingList)(nil),            // 9: membership.BookingList
}
var file_proto_membership_membership_proto_depIdxs = []int32{
	0, // 0: membership.BookingList.bookings:type_name -> membership.Booking
	1, // 1: membership.MembershipService.CreateBooking:input_type -> membership.CreateBookingRequest
	2, // 2: membership.MembershipService.CancelBooking:input_type -> membership.CancelBookingRequest
	3, // 3: membership.MembershipService.ReturnBooking:input_type -> membership.ReturnBookingRequest
	4, // 4: membership.MembershipService.GetUserCredits:input_type -> membership.GetUserCreditsRequest
	5, // 5: membership.MembershipService.DeductCredits:input_type -> membership.DeductCreditsRequest
	8, // 6: membership.MembershipService.GetUserBookings:input_type -> membership.GetUserBookingsRequest
	6, // 7: membership.MembershipService.AddCredits:input_type -> membership.AddCreditsRequest
	0, // 8: membership.MembershipService.CreateBooking:output_type -> membership.Booking
	0, // 9: membership.MembershipService.CancelBooking:output_type -> membership.Booking
	0, // 10: membership.MembershipService.ReturnBooking:output_type -> membership.Booking
	7, // 11: membership.MembershipService.GetUserCredits:output_type -> membership.CreditsResponse
	7, // 12: membership.MembershipService.DeductCredits:output_type -> membership.CreditsResponse
	9, // 13: membership.MembershipService.GetUserBookings:output_type -> membership.BookingList
	7, // 14: membership.MembershipService.AddCredits:output_type -> membership.CreditsResponse
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_membership_membership_proto_init() }
func file_proto_membership_membership_proto_init() {
	if File_proto_membership_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_membership_membership_proto_rawDesc), len(file_proto_membership_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_membership_membership_proto_goTypes,
		DependencyIndexes: file_proto_membership_membership_proto_depIdxs,
		MessageInfos:      file_proto_membership_membership_proto_msgTypes,
	}.Build()
	File_proto_membership_membership_proto = out.File
	file_proto_membership_membership_proto_goTypes = nil
	file_proto_membership_membership_proto_depIdxs = nil
}
